<!DOCTYPE html>
<!-- Copyright 2020, Brigham Young University - Idaho. All rights reserved. -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CSE 111 - Prepare</title>
    <link rel="icon" type="image/png" href="../site/icon.png">
    <link rel="stylesheet" type="text/css" href="../site/style.css">
    <script src="../site/color.js"></script>
</head>

<body onload="cse111.color.addSchemeHandler()">
<header>
    <div class="colorCtrl">&nbsp;</div>
    <div class="logo">
        <div class="upper">BYU</div>
        <div class="lower">Idaho</div>
    </div>
    <h2>CSE 111 | <span>Programming with Functions</span></h2>
</header>
<article>
    <h1>08 Prepare: Handling Errors</h1>
    <p>Errors and exceptional situations sometimes occur while a program
    is running. Such errors include a file that does not exist, a
    connection error from trying to connect to a server, data that
    cannot be found on a server, and calculations that produce undefined
    results. A well written program handles errors in a graceful manner
    that may include adjusting to an error, printing an error message
    for the user to see, and saving an error to a log file. During this
    lesson, you will learn to write code that handles errors that may
    occur while your Python program is running.</p>

    <h2>Videos</h2>
    <p>Watch these videos from Microsoft about error handling.</p>
    <ul class="links">
        <li><div><a target="_blank" href="https://channel9.msdn.com/Series/Intro-to-Python-Development/Python-for-Beginners-17-of-44-Error-Handling">Error Handling Concepts</a></div></li>
        <li><div><a target="_blank" href="https://channel9.msdn.com/Series/Intro-to-Python-Development/Python-for-Beginners-18-of-44-Demo-Error-Handling">Error Handling Demo</a></div></li>
    </ul>

    <h2>Concepts</h2>
    <p>Here are the Python programming concepts and topics that you
    should learn during this lesson.</p>

    <ol class="long">
        <li><div>An exception is a relatively rare exceptional event
        that sometimes occurs while a Python program is running. In
        Python, an error is a type of exception. There are many
        different <a target="_blank"
        href="https://docs.python.org/3/library/exceptions.html">built-in
        exceptions</a> that may occur while a Python program is
        running.</div></li>

        <li><div>When an exceptional event occurs, a Python function
        raises an exception which may be handled by code at another
        location in the executing Python program. The Python keyword to
        raise an exception is <code>raise</code>.</div></li>

        <li><div>The Python keywords to handle exceptions are
        <code>try</code>, <code>except</code>, <code>else</code>, and
        <code>finally</code>. The following example code contains the
        outline of a complete try-except-else-finally block. Read the
        code and its comments carefully to understand the correct syntax
        and organization of a try-except-else-finally block.

<div class="pre"><pre class="python"><em>try</em>:
    # Write normal code here. This block must include
    # code that falls into two groups:
    # 1. Code that may cause an exception to be raised
    # 2. Code that depends on the results from the code
    #    in the first group
<em>except ZeroDivisionError as ex:</em>
    # Code that the computer executes if the code in the
    # try block caused a ZeroDivisionError to be raised.
<em>except OSError as ex:</em>
    # Code that the computer executes if the code in
    # the try block caused an OSError to be raised.
<em>except ValueError as ex:</em>
    # Code that the computer executes if the code in
    # the try block caused a ValueError to be raised.
<em>except (RuntimeError, TypeError, NameError) as ex:</em>
    # Code that the computer executes if the code in the try
    # block raised a RuntimeError, TypeError, or NameError.
<em>except Exception as ex:</em>
    # Code that the computer executes if the code in the
    # try block caused any exception to be raised that was
    # not handled by one of the previous except blocks.
<em>except:</em>
    # Code that the computer executes if the code in the
    # try block caused anything to be raised that was
    # not handled by one of the previous except blocks.
<em>else:</em>
    # Code that the computer executes after the code
    # in the try block if the code in the try block
    # did not raise any exceptions.
<em>finally:</em>
    # Code that is executed after all the other code in
    # try, except, and else blocks regardless of whether
    # an exception was raised or not.</pre></div></div></li>

        <li><div>As shown in the example code above, when we want to
        write code that will handle exceptions, we first write the
        normal code that might cause an exception but does not handle
        exceptions inside a <code>try</code> block. Then we write
        <code>except</code> blocks to handle the exceptions. Each
        <code>except</code> block may handle one type of exception such
        as:
<div class="pre"><pre class="python">except ValueError as ex:</pre></div>
        Or each <code>except</code> block may handle several types of
        exceptions, such as:
<div class="pre"><pre class="python">except (RuntimeError, TypeError, NameError) as ex:</pre></div>
Or one <code>except</code> block may handle all possible types of
exceptions such as:
<div class="pre"><pre class="python">except Exception as ex:</pre></div>
Or a bare <code>except</code> block may handle anything that can
be raised, including <code>SystemExit</code>,
<code>KeyboardInterrupt</code> and <code>GeneratorExit</code>
such as:
<div class="pre"><pre class="python">except:</pre></div>
We must order except blocks from most specific at the top to
        least specific (most general) at the bottom.</div></li>

        <li><div>As shown in the example code above, following the
        <code>except</code> blocks, we may write an optional
        <code>else</code> block which the computer will execute if the
        <code>try</code> block does not raise any exceptions. It is
        uncommon to need to write code in the <code>else</code> block of
        <code>try</code> and <code>except</code>, and professional
        programmers almost never do it.</div></li>

        <li><div>As shown in the example code above, at the end of the
        exception handling code, we may write an optional
        <code>finally</code> block. The <code>finally</code> block
        contains code that the computer executes after all the other
        code in the <code>try</code>, <code>except</code>, and
        <code>else</code> blocks regardless of whether an exception was
        raised or not. The code in the <code>finally</code> block
        usually contains "clean up" code that frees resources that the
        code in the <code>try</code> block used. For example, if the
        code in the <code>try</code> block opens a file, the code in the
        <code>finally</code> block could close that file.</div></li>
    </ol>

    <h2>Example - Validating User Input</h2>
    <p>An example program that validates user input by handling
    exceptions is shown below. Notice there are two <code>try</code>
    blocks in the program: one at line&nbsp;2 in the <code>main</code>
    function and another at line&nbsp;40 in the <code>get_float</code>
    function.</p>

    <p>The <code>try</code> block at line&nbsp;40 is part of a loop that
    validates user input in the <code>get_float</code> function. Notice
    at line&nbsp;49 that the <code>except</code> block handles
    <a target="_blank" href="https://docs.python.org/3/library/exceptions.html#ValueError"><code>ValueError</code></a>
    which is the type of exception that the
    <a target="_blank" href="https://docs.python.org/3/library/functions.html#float"><code>float</code></a>
    function raises when it tries to convert text to a number but the
    text contains characters that are not numeric.</p>

    <p>The <code>try</code> block at line&nbsp;2 includes all the
    regular code in the <code>main</code> function. The except block at
    line&nbsp;18 will handle all types of runtime exceptions.
    <code>RuntimeError</code> is probably the most general type of
    exception that we want to handle in a Python program.
    <code>Exception</code> is more general than
    <code>RuntimeError</code>. However, <code>Exception</code> includes
    <code>SyntaxError</code>, and we don't want to handle
    <code>SyntaxError</code>. Instead, we want our program to crash for
    a syntax error and print the line number where the syntax error
    occurred. This is because syntax errors are caused by a programmer
    mistyping code and not by bad user input or missing files. We want a
    programmer to find and fix all syntax errors in a program long
    before the program is given to users.</p>

<div class="pre"><pre class="linenums">
1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9
10<br>11<br>12<br>13<br>14<br>15<br>16<br>17<br>18<br>19
20<br>21<br>22<br>23<br>24<br>25<br>26<br>27<br>28<br>29
30<br>31<br>32<br>33<br>34<br>35<br>36<br>37<br>38<br>39
40<br>41<br>42<br>43<br>44<br>45<br>46<br>47<br>48<br>49
50<br>51<br>52<br>53<br>54<br>55<br>56<br>57<br>58<br>59
</pre><pre class="python">
def main():
    <em>try:</em>
        gender = input("Enter your gender (M or F): ")

        weight = get_float("Enter your weight in kilograms: ", 1, 500)
        height = get_float("Enter your height in centimeters: ", 1, 300)
        age = get_float("Enter your age in years: ", 16, 120)

        bmr = basal_metabolic_rate(gender, weight, height, age)
        print(f"Your basal metabolic rate is {bmr} calories per day.")

    <em>except RuntimeError as ex:</em>
        print(type(ex).__name__, ex, sep=": ")


def get_float(prompt, lower, upper):
    """Get a number from the user, validate that the number is
    between a lower and upper bound, and return the number to the
    calling function. If the user does not enter a number between
    lower and upper inclusive, this function will prompt the user
    repeatedly until the user enters a number between lower and upper.

    param prompt: A string to display to the user.
    param lower: The lowest (smallest) number that the user may enter.
    param upper: The highest (largest) number that the user may enter.
    """
    while True:
        <em>try:</em>
            text = input(prompt)
            number = float(text)
            if number &lt; lower:
                print(f"{number} is too low.")
            elif number &gt; upper:
                print(f"{number} is too high.")
            else:
                break
        <em>except ValueError:</em>
            print(f"{text} is not a number.")
        print(f"Please enter a number between"
                f" {lower} and {upper}, inclusive.")

    return number


def basal_metabolic_rate(gender, weight, height, age):
    """Calculate and return a person's basal metabolic rate (bmr)
    in calories per day. weight must be in kilograms, height must
    be in centimeters, and age must be in years.
    """
    if gender.upper() == "F":
        bmr = 447.593 + 9.247 * weight + 3.098 * height - 4.330 * age
    else:
        bmr = 88.362 + 13.397 * weight + 4.799 * height - 5.677 * age
    return bmr


# Call the main function so that
# this program will start executing.
main()</pre></div>

    <h2>Example - Reading from a File</h2>
    <p>The example program shown below handles exceptions that might
    occur when the program opens and reads from a file. This program
    contains only one <code>try</code> block, which begins at
    line&nbsp;4 and includes all the regular code in the main function.
    This one try block has four <code>except</code> blocks at
    lines&nbsp;40, 44,&nbsp;48, and&nbsp;52.</p>

    <p>Each of the <code>except</code> blocks handles a different type
    of exception. The first three <code>except</code> blocks handle
    specific exceptions: <code>FileNotFoundError</code>,
    <code>PermissionError</code>, and <code>ZeroDivisionError</code>.
    The last <code>except</code> block handles
    <code>RuntimeError</code>, which is a general exception.
    <code>RuntimeError</code> is probably the most general type of
    exception that we want to handle in a Python program. The
    description above the first example program explains why.</p>

<div class="pre"><pre class="linenums">
1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9
10<br>11<br>12<br>13<br>14<br>15<br>16<br>17<br>18<br>19
20<br>21<br>22<br>23<br>24<br>25<br>26<br>27<br>28<br>29
30<br>31<br>32<br>33<br>34<br>35<br>36<br>37<br>38<br>39
40<br>41<br>42<br>43<br>44<br>45<br>46<br>47<br>48<br>49
50<br>51<br>52<br>53<br>54<br>55<br>56<br>57<br>58<br>59
60<br>61<br>62<br>63<br>64<br>65<br>66<br>67<br>68
</pre><pre class="python">
import csv


def main():
    <em>try:</em>
        # Open the fuel_usage.csv file.
        filename = "fuel_usage.csv"
        with open(filename, "rt") as usage_file:

            # Use the standard csv module to get
            # a reader object for the CSV file.
            reader = csv.reader(usage_file)

            # The first line of the CSV file contains headings
            # and not fuel usage data, so this statement skips
            # the first line of the CSV file.
            next(reader)

            # Print headers for the three columns.
            print("Date,Start,End,Gallons,Miles/Gallon")

            # Process each row in the CSV file.
            for row in reader:

                # From the current row of the CSV file, get
                # the date, the starting and ending odometer
                # readings, and the number of gallons used.
                date = row[0]
                start = float(row[1])
                end = float(row[2])
                gallons = float(row[3])

                # Call the miles_per_gallon function.
                mpg = miles_per_gallon(start, end, gallons)

                # Display the results for one row.
                mpg = round(mpg, 1)
                print(date, start, end, gallons, mpg, sep=",")

    <em>except FileNotFoundError as ex:</em>
        print(f"Error: cannot open {filename}"
                " because it doesn't exist.")

    <em>except PermissionError as ex:</em>
        print(f"Error: cannot read from {filename}"
                " because you don't have permission.")

    <em>except ZeroDivisionError as ex:</em>
        print(f"Error: {filename} contains a"
                " zero in the gallons column.")

    <em>except RuntimeError as ex:</em>
        print(type(ex).__name__, ex, sep=": ")


def miles_per_gallon(start, end, gallons):
    """Compute and return the average number of miles
    that a vehicle traveled per gallon of fuel.
    start and end are odometer readings in miles.
    gallons is a fuel amount in U.S. gallons.
    """
    mpg = abs(end - start) / gallons
    return mpg


# Call the main function so that
# this program will start executing.
main()</pre></div>

    <h2>Documentation</h2>
    <p>If the concepts above seem vague, these tutorials may clear some
    confusion for you:</p>

    <ul class="links">
        <li><div>Python Exceptions: <a target="_blank" href="https://realpython.com/python-exceptions/">An Introduction</a></div></li>
        <li><div>Official Python <a target="_blank" href="https://docs.python.org/3/tutorial/errors.html">Errors and Exceptions tutorial</a></div></li>
        <li><div>The Most <a target="_blank" href="https://realpython.com/the-most-diabolical-python-antipattern/">Diabolical Python Antipattern</a></div></li>
        <li><div>Understanding the <a target="_blank" href="https://realpython.com/python-traceback/">Python Traceback</a></div></li>
    </ul>

    <p>The official Python <a target="_blank"
    href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions">built-in
    exceptions reference</a> contains a list of all the built-in
    exceptions. It also includes the <a target="_blank"
    href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy">class
    hierarchy</a> for the built-in exceptions that is helpful for
    ordering <code>except</code> blocks from most specific to most
    general.</p>
</article>
<footer>
    <small>Copyright &copy; 2020, Brigham Young University - Idaho. All
    rights reserved.</small>
</footer>
</body>
</html>
